sudo: true
language: scala
jdk: oraclejdk8
scala:
- 2.12.6
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
services:
- redis-server
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt -name "*.lock" -print -delete
before_install:
- |
  if [[ $TRAVIS_PULL_REQUEST == false ]]; then
    openssl aes-256-cbc -K $encrypted_3889a889c453_key -iv $encrypted_3889a889c453_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
    tar xv -C travis -f travis/local.secrets.tar;
  fi
after_success:
- |
  if [[ $TRAVIS_PULL_REQUEST == false ]]; then
    sbt ++$TRAVIS_SCALA_VERSION publishSigned;
  fi
env:
  global:
  - secure: J41XiMrBV/BBXlCI8/15gPOhpQoirf89Uj256zvOGODs8L5Cx64W5CPq/ud+0g2MMGPNONBMh55qXPES6VI/ryQSazHHrDjr+tk11EGEkcF7akYxGV1wK3tLmHSOmkqNngcG3YbHQY2OP46xDurnpxZzWcoig+UA3QBqrGecjdMQCm0APGHXwJoWO5QIcL1BupdXFc1NJRigyBU9NefEIk/52dyZ5w8gDqrs+HcMOnpTOTY1OD9M/uo8DcQGyzUNGwlcuH+Oz7ag0hIcjjqclmj+b9iGVM/VKDoct1Rsf1VqKhG76WESv45Czn1BRW+Lx7E2HVUH7Jq2zxd9dFqK0rb5SQ3E4dA9BMW8EY+6UVLgvfdCqVpY+hHTTq3fFG16HqsZO5eAZKsAeWK0SYnggQS1un9Gy08A4jnJchQYd5cDHUQEzptyzuf9GxGmuu5I09/WUFp0yoqvZRRTbmUOlW4kmsVZC15plJh3ArgXG0HL5zaWahfbAi9p8bGWULomi+pkuGHz+0rhDiMWlqlNk7EQqKkAX9h0BsYA8wRrg0kulPxZy8FNt/hMjw4TPBgLcIWSBqBPp9PRscOqAX4q+F88PfTwouk7pLK6dQkf0NLeM1Fwtp1RGcYA+1SXxZ+1254kK4V/M4Oc81rW4L8z/8EZNcPY2Du1c6y+5nH9bMg=
  - secure: wE3VnQ1TJ7P/fmVXNZMs2mEamIICX6U8tUsLh0zBuvNeCMp0SFzQ+r+yWLdqp+TY8UiFE3HZriIuTWuKcn/s+rrFL46OgEifzAOwnAiioTIaDhN45OkZUDU/HM4bCsubpczl8hv9EqEh2adPDcJm5v/nKk+j+YEum8MrqsNL6irnmd56TpGQ0ZmzCcQ7rFesFPfF56msg9HPszgsYiLQMQ+n37q45ZoR5cjere5muUHxspsXnE9hXee9f/O7E2dnGdV5VSJKpSsWdvZXlS2zsx8oTJzZJTk00L+aGW8A6D+du0I9769TyC0t4gzze62s42sHcTG467itNYRbZUZUl1IMFAIb2H2e/uTGaC6Z5J3Lf/eiNbx8DCy44t8sNXYV6y7Pz7d1YOhNG+tijR+e04ObKSHBHkpc5FLkHiWXQJ2SfdMtWvCdwlx/lsAwqHgU4dxtzMaPePGNZuhL+6ZfN2YQxDn+dLGO1c1L5yD3903v8gxN7BU7kvnUksCPyOi/OJ7F7CY0zA5KsZX1TG47IdEIUaQuB1RY7towv+qRq+5eE0hokFkBc/xHqm+vLDJ9VX+9Bo/1K4DqDnU6YTCWmS6Y/1HdyzQpXK5x++woNkNpKuuMAkJdPaYXSr5B2lLquaG5IFyruSlhjB5v1SYpnQDd9kJTsrje+v01S2Zq8OQ=
  - secure: MTV4FvLWwGxBlvmylTG6L9jNSC1dWJHc8ErRZVlqemVt3k6SPaG5CXJt8Xbhz/jqYZIf5y3ZZy45imDDibDx/jTOCMtVZYvMB1wtjFl6VESco01J4SpuoXjpmH8zisq1vMeRR0OBs5CSVTddgllpdeF7ielzjtyOSjfGCI8biNqYWW1q1I88mZO5fLwbTw1kdiLHWVgMcdTIukHUUoH4IjY6qDOgHOP3zaisMHwAawR9+YYoSKd4CZxAzJ1zK89GF5oD4zDGZFF7cjGnrgfyypxc2F2sJTiwjh+83wHNclM9uwJqA66FtVunsne8s1Keqwu3FZlZKEXBMfwP/XHyJju9lSosaGq9u1HDxTFNUN0YIxhEsCffq//t7SmoNos1+2gl0MLcZi/7wvO/QSETgwcx7bNv3BJSAgGYlsDTrRiS7/EapOb7FPAqsehZOUe8JAQgYJYdxVcPthYJCVEVe3BB9NmchLv/pYSaE2Lhheo8NJayNDE68Z8A4GNQcCCWF93RiV1dbSSF3U8dbJ4Qh5wUHccIFPRC2pvXvvFqbuYXIsMCW4m4ewZ0zb5UMGmOHxLd3pQZoymPQYhnAoc1jXXVMnFO6TbleUhds4rE5uVnC6Se74T4332AUVjVLWarysK4fs9BdjphLsaHRDQIDA2l3iW8cuD6PKGUhRXsoQo=
